### PR TITLE
Adapt documentation to MongoDB Atlas

### PR DESCRIPTION
**Pull request by aviau**
Preview here: https://aviau.github.io/loopdocs/nightscout/new_user/#step-1-mongodb-atlas-account

Related Nightscout Pull Request here: https://github.com/nightscout/cgm-remote-monitor/pull/5893

### CODE REVIEW

**Comment by Jackie-O** [comment]
In the step for creating a new nightscout site you dont have the part about having to add the connection string for DB which is now mandatory.

**Comment by aviau** [comment]
> you dont have the part about having to add the connection string for DB which is now mandatory.

I do.

Screenshot from 2020-10-14 17-46-04

**Comment by aviau** [comment]
ping @Kdisimone

**Comment by Kdisimone** [comment]
I realize this is pending.

 Since the time you submitted this PR though, NS has updated their docs to be way more user friendly. I will likely just have loopdocs point directly to NS docs now instead. That will minimize chance of discrepancies between instructions as time goes on. The NS directions appear to cover the subject much better now for loop users, so probably unnecessary redundancy to have loopdocs for new NS sites alone. I just haven't had time to finish proofing NS docs to make the switch yet. 

Just a matter of time and as soon as I find some free time, I'll get this squared away.

**Comment by aviau** [comment]
Okay great! The new NS doc were actually based on this PR.

I'll close this.

**Comment by bjornoleh** [comment]
> I realize this is pending.
> 
> Since the time you submitted this PR though, NS has updated their docs to be way more user friendly. I will likely just have loopdocs point directly to NS docs now instead. That will minimize chance of discrepancies between instructions as time goes on. The NS directions appear to cover the subject much better now for loop users, so probably unnecessary redundancy to have loopdocs for new NS sites alone. I just haven't had time to finish proofing NS docs to make the switch yet.
> 
> Just a matter of time and as soon as I find some free time, I'll get this squared away.

Hi @Kdisimone , perhaps it would be good to point to https://loopkit.github.io/loopdocs/nightscout/new_user/#new-nightscout-users for setting up new NS now that mLab based databases are definitively a thing of the past. Every so often people come to the CGMITC FB group with partial setups after following Loopdocs, asking for help and support in completing the setup.

Thanks!

**Pull request closed without merging**
