### PR TITLE
Troubleshooting, Formatting and mkdocs updates

### PR DESCRIPTION
**Pull request by bfaloona**
Updated mkdocs.yml to enable two extensions. 
* admonition enables pretty text boxes to call out information
* permalink creates a handy link anchor to copy when you hover your mouse over any heading

Reworked Getting a Green Loop page

Updated readme

### CODE REVIEW

**Comment by bfaloona** [comment]
Would it be helpful if I split this PR into several smaller ones?

**Comment by ps2** [comment]
It looks like cgm_statuses.jpg and pump_statuses.jpg are missing. Could you add those?

**Comment by bfaloona** [comment]
@ps2 The initial plan was that @Kdisimone was going to capture, annotate, and add those images, but I now realize I did not call attention to that in my PR comments. I don't have a working Loop system to screenshot, so I'm not sure I'd be able to capture good images.

**Comment by ps2** [comment]
I'd like to get these changes in, but I don't want to have missing links on pages. If those sections still make sense w/o pictures, maybe you could just remove those links?

**Pull request merged**
