### PR TITLE
✏️ Fix broken anchors in links

### PR DESCRIPTION
**Pull request by ebouchut**
This PR will fix broken anchors present in links.
Issue #826 lists them all.

### CODE REVIEW

**Review by marionbarker — APPROVED** [review]
Very nice - thanks. LGTM

**Comment by ebouchut** [comment]
@marionbarker  I fixed most of them but need guidance on how to fix the ones below that give me a hard time.
Feel free to push a commit with the last fixes directly to this branch in case you have a few nanos.

- WARNING -  Doc file `loop-3/add-cgm.md` contains a link `../version/code-custom-edits.md#libre-support-for-loop-32x-code`, but the doc 'version/code-custom-edits.md' does not contain an anchor `#libre-support-for-loop-32x-code`.
- WARNING -  Doc file `operation/algorithm/prediction.md` contains a link `../../version/code-custom-edits.md#exponential-insulin-curve`, but the doc `version/code-custom-edits.md` does not contain an anchor `#exponential-insulin-curve`.
- WARNING -  Doc file 'operation/loop-settings/cgm.md' contains a link '../../version/code-custom-edits.md#libre-support-for-loop-32x-code', but the doc 'version/code-custom-edits.md' does not contain an anchor `#libre-support-for-loop-32x-code`.
- WARNING -  Doc file `operation/loop-settings/rileylink.md` contains a link `../../loop-3/displays-v3.md#error-messages`, but the doc `loop-3/displays-v3.md` does not contain an anchor `#error-messages`.

**Comment by ebouchut** [comment]
I had to do some archeology to detect the changes and practice my git CLI.
I finally found a use case for  `git log -S ...` and `git log -G ...` 😀.

**Comment by marionbarker** [comment]
I'm going to go ahead with PR 830 in case anyone else has a can't upload to testflight error before I can look at this.

**Comment by marionbarker** [comment]
I merged in main, updated the final missing links and pushed to your branch.
Please review (fix if needed) and then merge.

**Review by ebouchut — COMMENTED** [review]
LGTM.

**Comment by ebouchut** [comment]
@marionbarker Thank you for taking the time to fix the final anchors.

**Comment by ebouchut** [comment]
This PR fixes #826

**Pull request merged**
