### PR TITLE
Update Trio References

### PR DESCRIPTION
**Pull request by MikePlante1**

### CODE REVIEW

**Review by ebouchut — COMMENTED** [review]
👍 LGTM

**Comment by ebouchut** [comment]
There is another occurrence in [`releases`](https://github.com/LoopKit/loopdocs/blob/fbb0250adfe8c657cd738e899eb2ac8d2ac9b253/docs/version/releases.md?plain=1#L185).

**Comment by MikePlante1** [comment]
> There is another occurrence in [`releases`](https://github.com/LoopKit/loopdocs/blob/fbb0250adfe8c657cd738e899eb2ac8d2ac9b253/docs/version/releases.md?plain=1#L185).

That one is still accurate. iAPS uses the same App Group as Loop, whereas Trio uses its own.

**Comment by MikePlante1** [comment]
Closing, because @marionbarker already has it covered.

**Pull request closed without merging**
