### PR TITLE
Increase basal rate when at correction range

### PR DESCRIPTION
**Pull request by Nightfoxy**
Loop increases temp basal rates (or delivers auto boluses) when the entire prediction is at or above the correction range and eventual BG is higher than the correction range. This makes the information consistent with the second RESUME example.

### CODE REVIEW

**Comment by Kdisimone** [comment]
Sorry. Edits aren't correct as written. Suspend threshold is still relevant

**Comment by Nightfoxy** [comment]
Per the second RESUME example (https://loopkit.github.io/loopdocs/operation/algorithm/temp-basal/#resume-basal-rate), 

> "If the eventual blood glucose is above the correction range, and the predicted glucose values have a **temporary excursion below the correction range but still above the suspend threshold**, then Loop will _resume the current scheduled basal rate_."

Current text: 

> If the eventual blood glucose is greater than the correction range and **all of the predicted glucose values are above the suspend threshold**, then Loop will issue a temporary basal rate that is higher than the current basal rate to bring the eventual blood glucose down to the correction target.

So, its not enough for the prediction to be above the suspend threshold. If part of the prediction is above suspend but below the correction range, then loop will not issue an increased temp basal. It will only resume scheduled basal. 

Let me know if I am misunderstanding something. Thanks.

**Comment by Kdisimone** [comment]
Your edit takes out the suspend threshold text. Revise your edits to be more accurate and consistent with what you're trying to specify then?

**Comment by Kdisimone** [comment]
Make your edits match what you're trying to say above. Currently the edits do not match those comments. 


https://github.com/LoopKit/loopdocs/pull/183/files

**Comment by Nightfoxy** [comment]
Pull request text:
> If the eventual blood glucose is greater than the correction range and all of the predicted glucose values are **equal to or above the correction range**,...

That is the change I made and it is consistent with what I described. Its only making an assumption that the correction range is above the suspend threshold. I don't see the need to mention the suspend threshold. What I described above is a condition that fits within the current text that will actually NOT result in an increased temp basal rate, but a resume of scheduled basal. This is already described on that page.

All of the prediction must be within or above the correction range and eventual BG higher than the correction range to trigger an increased temp basal rate. Do you have another suggestion for how to say that?

Would this be better?
> If the eventual blood glucose is greater than the correction range and all of the predicted glucose values are **above the suspend threshold and equal to or above the correction range**,...

**Comment by Nightfoxy** [comment]
@Kdisimone , Do you think this section needs to refer to the suspend threshold? I'll figure out a way to re-write it if so. Other than that, do you have any concerns with its accuracy? 

There is conversation in the FreeAPS thread about how this should work and tightening this section up will help.

**Comment by Nightfoxy** [comment]
Please help me understand what should be changed. I want to help with LoopDocs and I am open to feedback.

From what I can tell, the current text for increasing temp basal rates is inaccurate since the definition intersects with the definition for the "resume" condition in the case where glucose values are above suspend but below the correction range. 

I'd like to keep the change consistent with your wording, so if you have another way to say it, let's go with that.

**Pull request merged**
