### PR TITLE
Update docs to reflect that omnipod-testing has been merged into dev

### PR DESCRIPTION
**Pull request by j4cbo**
Update docs to reflect that omnipod-testing has been merged into dev, so either dev or omnipod-testing are suitable for omnipod users.

### CODE REVIEW

**Comment by Kdisimone** [comment]
This merge has not been done yet, and docs will reflect it when it does happen.

**Comment by j4cbo** [comment]
Wasn't it merged in https://github.com/LoopKit/Loop/pull/997 ...?

**Comment by Kdisimone** [comment]
No, that is not the omnipod-testing branch.  That is the omnipod-testing-integrate branch. There are still some things being sorted out in dev. I assure you when the full switch of pods to dev branch is ready, the docs will be updated too.

**Comment by Kdisimone** [comment]
I won't be merging this change. There are things in development branch that still provide warnings and strange messages that will be confusing to people currently. That is not what I want to steer people to yet. Please be patient. This is a large community and dev is NOT quite ready to have people jumping on there yet. People should still be using omnipod-testing branch. There's a reason the docs are the way they are right now.

**Comment by j4cbo** [comment]
Would you accept a PR that removed links to the dev branch from the "build loop" page, and replaced them with discussion of master, omnipod-testing, and a mention of "there are other branches for development, but they are even less stable and should not be used by most users"?

The reason I'm pushing on this is that I was talking on Facebook to someone who believed that omnipod support didn't exist at all in the dev branch. The way this page is currently written strongly suggests that. And I don't EVER want to say to someone "the docs are wrong"... I would rather have what's in the docs be as clear as possible and omit complication that will confuse the majority of users.

**Comment by Kdisimone** [comment]
How about you explain to people that the docs represent the main form of communication to a wide range of general public users?  How about you explain to that person that the biggest problem with general public using the Loopdocs is that there is so much to digest and so much new foreign terms that including a mention l to “dev” branch right now including omnipod support could create a genuine support burden unnecessarily?  How about explaining to people that sometimes Loopdocs might not get into the deep weeds of details like that because the people who read them once may not come back for updated info later?  So they will not understand that dev branch is not *really* omnipod support right now. And anyone telling people that dev is “supporting” omnipod right now is just adding to the inevitable support burden currently. Explain instead that dev is in very active development for omnipod support and overrides at same time. Devs are not recommending to steer people to dev branch right now. So why confuse the issue? Wait. Patience for when the omnipod dosing is worked out. Until some other recent dev bugs are worked out. Telling people dev supports omnipod right now unnecessarily confuses the issue of which one people should choose today. It is still omnipod-testing. That is where steering should be. 

And I’ve now watched Looped general public users be unable to discern the subtly of github descriptions. This would be a burden.

**Pull request closed without merging**
