### PR TITLE
Update to point to Nightscout documentation.

### PR DESCRIPTION
**Pull request by ELUTE**

### CODE REVIEW

**Comment by bjornoleh** [comment]
Thanks @ELUTE, this is very much needed. Perhaps add a hint about that video not being up to date too? Alternatively remove it to avoid a potential source of confusion. 

Thank you and merry Christmas!

**Comment by Nightfoxy** [comment]
Could change the last line to link to this page for instructions:
https://loopkit.github.io/loopdocs/operation/loop-settings/services/

**Comment by bjornoleh** [comment]
Hi @ps2, could you please have a look here and perhaps see if this PR can be merged soon? There are quite a few failed attempts at setting up Nightscout that require support from the community, primarily because of outdated info in Loopdocs.

**Comment by Kdisimone** [comment]
I'm going to close this since it was quicker to just make the changes fresh instead of resolving the conflicts in the PR.  The changes have been made and deployed to Loopdocs now.  Thanks!

**Pull request closed without merging**
