### PR TITLE
Updates to Retrospective Correction description

### PR DESCRIPTION
**Pull request by bedtime4bonzos**
Removed sigma notation from BG_vel calculation and changed to evaluate at current time 0, updated diagrams so direction of discrepancy is consistent with RC effect, updated language for consistency with diagrams.

### CODE REVIEW

**Comment by bedtime4bonzos** [comment]
Meant to squash commits

**Comment by bedtime4bonzos** [comment]
Re-opening.  Let me know if you want me to re-submit as fewer commits.  Thanks!

**Comment by ebouchut** [comment]
Thank you @bedtime4bonzos for your 🦅👁️ on the algorithm section.  
Regarding the PR, no need to squash commits.  
Personally, I prefer atomic commits with descriptive comments.

I would suggest reducing the size of the images. Use [`ImageOptim`](https://imageoptim.com/mac ) or whatever tool you are used to.

```shell
# Install ImageOptim App on Mac
brew install imageoptim
```
Otherwise, use the optimized images in this [zip file](https://github.com/LoopKit/loopdocs/files/12111936/Archive.zip).

**Comment by bedtime4bonzos** [comment]
Thanks @ebouchut - Good catch.  Your files were slightly smaller than the pngs I got from the online tool at the link you provided, so I just went with yours.

**Comment by ebouchut** [comment]
@bedtime4bonzos 
Since my suggestion was to save space on the images, I took the liberty of rebasing the PR branch to remove the 2 commits with the uncompressed images (which we will not be using).
I forgot to ask you about this yesterday.

I also changed the message of the last commit with the compressed images.

Thanks again for your contribution 👍.

**Comment by bedtime4bonzos** [comment]
@ebouchut  Thanks for cleaning it up!

**Pull request merged**
