### PR TITLE
🚸  UX Improvement: Open external links in a new window

### PR DESCRIPTION
**Pull request by ebouchut**
This PR improves LoopDocs' _User Experience_ when clicking a link to an external site.

Links to external websites will now open in a new window (or a new tab depending on the browser's configuration) whereas before it was opening in the same window.

The PR also:
- appends the attribute list suffix `{: target="_blank" }` to existing external links so that they open in a new window
- replaces mentions of `right-click the link to open in a new tab` with `click ...`.
- Updates the _README_ to explain how to make an external link open in a new window

Most non-tech-savvy users do not know how to open links in a new tab/window using `⌘ Click` (Command-Click) on Mac or `⌃ Click` (Control-Click) on Windows. The goal is to help them so that they do not lose track of where they have been in LoopDocs as soon as they close the new window.

🙏🏻 Thank you @dnzxy for suggesting this improvement:

```markdown
[Link Label](Link URL){:target="_blank"}
```

### CODE REVIEW

**Comment by marionbarker** [comment]
I have a question. Are there cases where having a website open a new tab automatically could be blocked. What happens in that case.

**Review by ebouchut — COMMENTED** [review]
LGTM.
Tested the links in Chrome Deskop and Safari Mobile.

**Comment by ebouchut** [comment]
> I have a question. Are there cases where having a website open a new tab automatically could be blocked. What happens in that case.

Will check this.

**Comment by dnzxy** [comment]
> I have a question. Are there cases where having a website open a new tab automatically could be blocked. What happens in that case.

Nothing should happen. If you are opening a new tab that needs logging in and you do not have an active session cached via cookies, you will be prompted to login. For all other instances, nothing would happen. This is doing the exact same thing las either cmd+click, right click „open in new tab“, right click copy link and open tab manually and paste then enter.

**Comment by ebouchut** [comment]
ℹ️ For the record, below is the [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) (regex) I used in [Obsidian](https://obsidian.md) to search for external links:

```
/\(https?:\/\/[^\)]+\)(?!\{:?[ \t]*target="_blank"[ \t]*\})/
```

**Comment by ebouchut** [comment]
Using `target="_blank"` may expose to _reverse tabnagging_.  
[According to caniuse.com](https://caniuse.com/rel-noopener) recent browser versions no longer suffer from this.  
To mitigate "tab-napping" attacks, in which a new tab/window opened by a victim context may navigate that opener context, the HTML standard changed to specify that anchors that contain `target="_blank"` should behave as if `rel="noopener"` is set. 


## What is Reverse Tabnabbing?

> 🤖> "Reverse tabnabbing" is a type of phishing attack where a page linked from the target page is able to rewrite that page, often replacing it with a phishing site(1). Here's how it works:
>
> - [1](https://owasp.org/www-community/attacks/Reverse_Tabnabbing). The victim clicks a link on a legitimate site. This link opens a new tab because of the `target="_blank"` property in the HTML link².
> - [2](https://www.comparitech.com/blog/information-security/reverse-tabnabbing/). While the victim is looking at the new tab, the malicious site forces a redirect of the original tab to a fake website that looks exactly like the original.
> - 3. The fake website prompts the victim to re-enter their credentials. If the victim enters their credentials into the fake website, they've just handed their credentials over to the attacker².
> 
> This attack is possible when the source site uses a `target` instruction in an HTML link to specify a target loading location that does not replace the current location (1). It's also possible for links opened via the `window.open` JavaScript function(1).
> 
> To prevent reverse tabnabbing, you can add `rel="noopener"` or `rel="noreferrer"` to your links. This ensures that the new page does not have access to the `window.opener` object of the original page, thus preventing potential security issues¹. Here's an example:
> 
> ```html
> <a href="https://somewhere.example.org" target="_blank" rel="noopener">Click me</a>
> ```
> 
> Please note that while modern browsers have implicit `rel="noopener"` for links with `target="_blank"`, there are still some browsers that don't support it, so it's a good practice to include `rel="noopener"`¹.
> 
> Sources: 
> - (1) What is tabnabbing?
>   - https://www.comparitech.com/blog/information-security/reverse-tabnabbing/
>   - https://owasp.org/www-community/attacks/Reverse_Tabnabbing
> - How to prevent tabnabbing?
>   - (2) [What is reverse tabnabbing and how can you prevent it? (Comparitech)](https://www.comparitech.com/blog/information-security/reverse-tabnabbing/.
>   - (3) [What is Reverse Tabnabbing and What Can You Do to Stop It? (securityintelligence)](https://securityintelligence.com/posts/what-is-reverse-tabnabbing-and-what-can-you-do-to-stop-it/)
>   - [About `rel="noopener"`. What problm does it solve?](https://mathiasbynens.github.io/rel-noopener/)

**Comment by dnzxy** [comment]
I don’t really see that as a realistic thread for LoopDocs, sorry.

**Comment by ebouchut** [comment]
This is something to keep in mind and take care of if we decide to use local/session storage someday.

**Comment by ebouchut** [comment]
Added an up-right arrow icon next to links that open in a new window/tab in 1841b94 .

ericbouchut com_loopdocs_nightscout_overview_

This can be improved using [the usual one](https://fontawesome.com/icons/up-right-from-square?f=classic&s=solid) instead later on, but I want to materialize them eight away.

**Pull request merged**
